language: node_js
addons:
  sauce_connect: true
node_js:
  - "0.10"
  - "0.8"
services: mongodb
env:
  - secure: "MPXT3ljlirTlmpxOlLJpnQiCOuMmWupDSK9JyIElBlcFicft1xIGDNWD61PACgAD23gHhaBXN6vo4aJGwnOGx+jLiOUtR4NHZMXqNcbVOcET9uoUTM7KZVkYbFNYZCA3iBjrkhYEGRW4xs14dcjiQ3TSB63IGm1nBW7OOLodGK0="
  - secure: "hLRso5V54kVwUpL/r/N6v+xAo3miMtU06YhX43QCkGObopk7pms+wAMCUb1Zcp7n7+cobcSmm0UUKNNfBBdgzo5AWxr0XFxfcyon+6EnSLxFwdm97hxYYFlmQHhVYinffIAwfIAPmQhr/MfwL5pa6ccy8qLYyjuogPK3qW95kwc="

